customer:
  email: "test@example.com"
  password: "Test@123"
  phone: "9876543210"
  firstname: "John"
  lastname: "Doe"
  address: "1 River St, Schenatedy, NY"
  city: "New York"
  state: "NY"
  ssn: "123-45-6789"

product:
  plan: "UMAXX ULTRA"
  modem: "Nokia FWA 12"
  zip: "10001"

# --- Web Element XPaths ---
# This file stores XPaths for UI automation, mapped to descriptive keys.

nav_toggler_button: "//button[contains(@class, 'navbar-toggler')]"
nav_link_2: "//*[@id=\"nav-link-2\"]"
#section_3_link: "//*[@id="nav-link-2"]"
plans_section_link: "//*[@id=\"plans-section\"]/div/div[1]/div/div[3]/a"
coverage_code_input: "//*[@id=\"coverage-code\"]"
free_hbo_email_input: "//*[@id=\"free_hbo_email_address\"]"
zip_form_submit_button: "//*[@id=\"zip-form\"]/div[3]/button"
zip_form_confirm_button: "//*[@id=\"zip-form-confirm\"]/div[1]/label[3]/button[2]"
nokia_element: "//*[@id=\"nokia\"]"
accept_checkbox: "//*[@id=\"accept-checkbox\"]"
newsletter_checkbox: "//*[@id=\"newsletter-checkbox\"]"
offers_checkbox: "//*[@id=\"offers-checkbox\"]"
new_order_complete_button: "//*[@id=\"new_order\"]/div[15]/div/div/button"
subscription_plan_link_post_order: "//*[@id=\"subscription-plan-box\"]/div/div/div/a"
make_payment_button: "//*[@id=\"checkout-stripe-payment-options\"]/div/div[2]/div/div[3]/div/div/div/form/button"
complete_purchasing_button: "//*[@id=\"payment-form\"]/div/div/div/div[3]/div/div[2]/div/button/div[3]"
home_nav_link: "//*[@id=\"nav-link-0\"]"